apiVersion: v1
kind: Service
metadata:
  name: geth-service
spec:
  selector:
    app: geth
  ports:
    - name: rpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: p2p
      protocol: UDP
      port: 30303
      targetPort: 30303
  type: ClusterIP
