apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-node
spec:
  serviceName: geth-service
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:stable
          command: ["geth"]
          args:
            [
              "--dev",
              "--http",
              "--http.api",
              "eth,net,web3,miner,admin,txpool,personal",
            ]
          # args:
          #   - "--http"
          #   - "--http.addr=0.0.0.0"
          #   - "--http.vhosts=*"
          #   - "--http.api=eth,net,web3,personal,miner,admin"
          #   - "--networkid=1337"
          #   - "--mine"
          #   - "--allow-insecure-unlock"
          #   - "--nodiscover"
          #   - "--verbosity=3"
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 30303
              name: p2p
              protocol: UDP
          volumeMounts:
            - name: geth-data
              mountPath: /root/.ethereum
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
  volumeClaimTemplates:
    - metadata:
        name: geth-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
