apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-node
spec:
  serviceName: geth-service
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:stable
          args:
            - "--syncmode=snap"
            - "--http"
            - "--http.addr=0.0.0.0"
            - "--http.api=eth,net,web3,debug"
            - "--metrics"
            - "--metrics.addr=0.0.0.0"
            - "--networkid=1337"
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 30303
              name: p2p
              protocol: UDP
          volumeMounts:
            - name: geth-data
              mountPath: /root/.ethereum
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
  volumeClaimTemplates:
    - metadata:
        name: geth-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
